version: "3"

services:
  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  pact_broker_app:
    image: dius/pact-broker
    links:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres

  # Nginx is not necessary, but demonstrates how
  # one might use a reverse proxy in front of the broker,
  # and includes the use of a self-signed TLS certificate
  pact_broker:
    image: nginx:alpine
    volumes:
      - ./ssl/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl
    ports:
      - "8443:443"
      - "80:80"

  can_i_deploy:
    image: pactfoundation/pact-cli
    environment:
      PACT_BROKER_BASE_URL: https://pact_broker:443
      SSL_CERT_FILE: /tmp/cacert.crt
    volumes:
      - ${PWD}/ssl/cacert.crt:/tmp/cacert.crt
    command: broker can-i-deploy --pacticipant "Example App" --latest
